---
title: "Publications"
---

A list of publications from the Pichugin Lab. For the most up-to-date list, see [Google Scholar](https://scholar.google.com) or [ORCID](https://orcid.org).

---

## Preprints

::: {.publication-entry}
**[Title of Preprint]**  
A. Pichugin, [Co-authors]  
*bioRxiv* (2025)  
[{{< fa file-pdf >}} PDF](#){.btn .btn-sm .btn-outline-danger} [{{< fa brands github >}} Code](#){.btn .btn-sm .btn-outline-dark}
:::

---

## Journal Articles

::: {.publication-entry}
**[Title of Article]**  
A. Pichugin, [Co-authors]  
*Journal Name* **Vol**(Issue), pp–pp (Year)  
[{{< fa file-pdf >}} PDF](#){.btn .btn-sm .btn-outline-danger} [{{< fa link >}} DOI](#){.btn .btn-sm .btn-outline-primary} [{{< fa brands github >}} Code](#){.btn .btn-sm .btn-outline-dark}
:::

::: {.publication-entry}
**[Title of Article]**  
A. Pichugin, [Co-authors]  
*Journal Name* **Vol**(Issue), pp–pp (Year)  
[{{< fa file-pdf >}} PDF](#){.btn .btn-sm .btn-outline-danger} [{{< fa link >}} DOI](#){.btn .btn-sm .btn-outline-primary}
:::

---

## Book Chapters

::: {.publication-entry}
**[Title of Chapter]**  
A. Pichugin, [Co-authors]  
In *Book Title*, eds. [Editors]. Publisher, City (Year)  
[{{< fa link >}} DOI](#){.btn .btn-sm .btn-outline-primary}
:::

---

## Theses

::: {.publication-entry}
**[Title of PhD Thesis]**  
A. Pichugin  
*[Institution]* (Year)  
[{{< fa link >}} Link](#){.btn .btn-sm .btn-outline-primary}
:::
